kind: template
load: pipeline-builder.star
data:
  builds:
    # test builds during PRs
    # aws-cli-chamber-helm
    - name: build-ci-cd-aws-cli-chamber-helm-on-pr
      repository: ghcr.io/sidestream-tech/dockerfiles/aws-cli-chamber-helm
      path_to_dockerfile: ci-cd/aws-cli-chamber-helm/Dockerfile
      path_to_context: ci-cd/aws-cli-chamber-helm/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - pull_request
    - name: build-ci-cd-docker-in-docker-chamber-on-pr
      repository: ghcr.io/sidestream-tech/dockerfiles/docker-in-docker-chamber
      path_to_dockerfile: ci-cd/docker-in-docker-chamber/Dockerfile
      path_to_context: ci-cd/docker-in-docker-chamber/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - pull_request
    - name: build-ci-cd-aws-cli-chamber-helmsman-on-pr
      repository: ghcr.io/sidestream-tech/dockerfiles/aws-cli-chamber-helmsman
      path_to_dockerfile: ci-cd/aws-cli-chamber-helmsman/Dockerfile
      path_to_context: ci-cd/aws-cli-chamber-helmsman/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - pull_request
    - name: build-ci-cd-aws-az-cli-chamber-helm-on-pr
      repository: ghcr.io/sidestream-tech/dockerfiles/aws-az-cli-chamber-helm
      path_to_dockerfile: ci-cd/aws-az-cli-chamber-helm/Dockerfile
      path_to_context: ci-cd/aws-az-cli-chamber-helm/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - pull_request

    # publish images on merge to main
    # publish aws-cli-chamber-helm:main and aws-cli-chamber-helm:$MAIN_COMMIT_SHA
    - name: publish-ci-cd-aws-cli-chamber-helm-merge-main
      repository: ghcr.io/sidestream-tech/dockerfiles/aws-cli-chamber-helm
      tags:
        - "main"
        - "${DRONE_COMMIT_SHA}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/dockerfiles
      path_to_dockerfile: ci-cd/aws-cli-chamber-helm/Dockerfile
      path_to_context: ci-cd/aws-cli-chamber-helm/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - push
        branch:
          - main

    # publish ci-cd-docker-in-docker-chamber:main and ci-cd-docker-in-docker-chamber:$MAIN_COMMIT_SHA
    - name: publish-ci-cd-docker-in-docker-chamber-merge-main
      repository: ghcr.io/sidestream-tech/dockerfiles/docker-in-docker-chamber
      tags:
        - "main"
        - "${DRONE_COMMIT_SHA}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/dockerfiles
      path_to_dockerfile: ci-cd/docker-in-docker-chamber/Dockerfile
      path_to_context: ci-cd/docker-in-docker-chamber/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - push
        branch:
          - main

    - name: publish-ci-cd-aws-cli-chamber-helmsman-merge-main
      repository: ghcr.io/sidestream-tech/dockerfiles/aws-cli-chamber-helmsman
      tags:
        - "main"
        - "${DRONE_COMMIT_SHA}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/dockerfiles
      path_to_dockerfile: ci-cd/aws-cli-chamber-helmsman/Dockerfile
      path_to_context: ci-cd/aws-cli-chamber-helmsman/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - push
        branch:
          - main

    - name: publish-ci-cd-aws-az-cli-chamber-helm-merge-main
      repository: ghcr.io/sidestream-tech/dockerfiles/aws-az-cli-chamber-helm
      tags:
        - "main"
        - "${DRONE_COMMIT_SHA}"
      labels:
        - key: org.opencontainers.image.source
          value: https://github.com/sidestream-tech/dockerfiles
      path_to_dockerfile: ci-cd/aws-az-cli-chamber-helm/Dockerfile
      path_to_context: ci-cd/aws-az-cli-chamber-helm/
      tags_to_cache_from:
        - "main"
      trigger:
        event:
          - push
        branch:
          - main

  pipelines:
    - kind: pipeline
      type: kubernetes
      name: check-markdown-lint-dockerfiles
      steps:
        - name: check-markdown-links
          image: node:lts
          commands:
            - npm i -g markdown-link-check
            - find . -name "*.md" | xargs -n1 markdown-link-check

        - name: lint-dockerfiles
          image: hadolint/hadolint:latest-debian
          commands:
            - find . -name Dockerfile | xargs -n1 hadolint --failure-threshold warning

        - name: success
          image: alpine
          depends_on: ["check-markdown-links", "lint-dockerfiles"]
          commands:
            - echo "success"

      trigger:
        event:
          - pull_request
