kind: template
load: pipeline-builder.star
data:
  pipelines:
    - kind: pipeline
      type: kubernetes
      name: check-markdown-lint-dockerfiles
      steps:

        - name: success
          image: alpine
          depends_on: ["check-markdown-links", "lint-dockerfiles"]
          commands:
            - echo "success"

      trigger:
        event:
          - pull_request
